version: "3.8"

services:
  mongo:
    image: mongo
    restart: always

    environment:
      MONGO_INITDB_DATABASE: access
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_NON_ROOT_USERNAME: telicent-access
      MONGO_NON_ROOT_PASSWORD: password
      
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - db_data:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - 8091:8091
   
    environment:
      DEPLOYED_DOMAIN: http://localhost:8080
      MONGO_URL: mongo:27017
      MONGO_COLLECTION: access
      MONGO_USER: telicent-access
      MONGO_PWD: password
      OPENID_PROVIDER_URL: development
      SCIM_ENABLED: false

    
    command: ["/app/wait-for.sh", "mongo:27017", "--", "node", "dist/index.js"]
  ui:
    # image: telicent/telicent-access:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
   
    ports:
      - "8080:8080"
volumes:
  db_data:


