name: Test feature branch
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - frontend

jobs:
  quality:
    name: Run unit tests
    uses: telicent-oss/shared-workflows/.github/workflows/feature-branch-test.yml@main
    secrets: inherit
    with:
      working-directory: frontend

