name: Test feature branch
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - frontend

jobs:
  quality:
    name: Run unit tests
    uses: telicent-oss/shared-workflows/.github/workflows/feature-branch-test.yml@javascript-test-feature-branch/yarn-test-command
    secrets: inherit
    with:
      working-directory: frontend
      javascript-test-feature-branch/yarn-test-command: test:ci
