name: Test Access API
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - src

jobs:
  quality:
    name: Run unit tests
    uses: Telicent-oss/shared-workflows/.github/workflows/javascript-feature-branch-test.yml@main
    secrets: inherit
