name: Test Access API
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - src
  #add dispatch in case job fails and needs to be manually executed
  workflow_dispatch:

jobs:
  quality:
    name: Run unit tests
    uses: telicent-oss/shared-workflows/.github/workflows/feature-branch-test.yml@main
    secrets: inherit
